Front service passengers
Dhauzur/front-sochamar pull request #24
Opened 2020-02-12 21:25 UTC by Fairplaay

2020-02-12 22:59 UTC, JavierCollipal commented on src/components/ui/autocomplete/autocomplete.md
> +
Buen detalle el añadir un .md para un componente que vamos a volver a utilizar en la app.

2020-02-12 23:03 UTC, JavierCollipal commented on src/store/modules/Lodging.js
> +		state.lodgingPassengers = value;
En la mutacion setAllLodgingPassengers, seria bueno cambiar el nombre de value a values.
Es un detalle, pero da a entender que esa función siempre asignara n valores y no un solo valor.

2020-02-12 23:11 UTC, JavierCollipal approved these changes
En general el codigo esta bien estructurado.
Veo que se cambio parte del codigo en company y reports, simplificando llamadas directas a la store y cambiándolas por ...mapActions

2020-02-13 03:08 UTC, Dhauzur requested changes

2020-02-13 03:08 UTC, Dhauzur commented on src/components/lodgings/EditLodging.vue
> +				: this.$toasted.show(`ya ha sido seleccionado en esta fecha`, {
"Ya existe un pasajero para el rango de fecha selecionado"

2020-02-13 03:08 UTC, Dhauzur commented on src/components/lodgings/EditLodging.vue
> +			fetchAllPassengers: 'Passengers/fetchAllPassengers',
No deberia cargar los pasajeros ya que  estarian en el store del front. 
Es decir, deberia solo traer los pasajeros de un getter. Y el fetch passanger, deberia cargarse en el mounted de lodgings.vue o un reload passanger si es que agrego un nuevo pasajero. Me hago entender?

2020-02-13 03:08 UTC, Dhauzur commented on src/components/ui/autocomplete/autocomplete.md
> +
GENIAL

2020-02-13 03:08 UTC, Dhauzur commented on src/views/Company.vue
> +				lodging: '',
muchisimas gracias

2020-02-13 16:30 UTC, Dhauzur approved these changes

2020-02-13 16:30 UTC, merged